CUSTOMER_ID_COLS = ['رقم الهوية', 'الهوية', 'هوية العميل']
DEBT_ID_COLS = ['رقم المديونية', 'رقم المديونيه']
PORTFOLIO_COLS = ['المحافظ', 'المحفظة', 'اسم المحفظة']
COLLECTOR_COLS = ['المحصل', 'اسم المحصل', 'الموظف']
SUPERVISOR_COLS = ['المشرف', 'اسم المشرف']
USERNAME_COLS = ['اسم المستخدم', 'اليوزر', 'المستخدم']
DEBT_AMOUNT_COLS = ['مبلغ الميدونية', 'مبلغ المديونية', 'المديونية']
PAID_DOC_COLS = ['السدادات الموثقة', 'سدادات موثقة']
REMAINING_DOC_COLS = ['متبقي سداد موثق', 'المتبقي الموثق']
PAID_CONTRACT_COLS = ['سدادات العقود', 'سداد العقد']
REMAINING_CONTRACT_COLS = ['متبقي سداد العقد']
MAIN_STATUS_COLS = ['الحالة الرئيسية', 'الحالة']
SUB_STATUS_COLS = ['الحالة الفرعية']
FOLLOWUP_DATE_COLS = ['تاريخ المتابعة', 'أخر متابعة للعميل', 'آخر متابعة للعميل']
FOLLOWUP_NOTE_COLS = ['المتابعة', 'ملاحظة المتابعة']
ASSIGNMENT_DATE_COLS = ['تاريخ الاسناد', 'تاريخ الإسناد', 'تاريخ التوزيع']
BRANCH_COLS = ['الفرع']
PAYMENT_AMOUNT_COLS = ['مبلغ السداد', 'قيمة السداد', 'مبلغ الدفع']
PAYMENT_DATE_COLS = ['تاريخ السداد', 'تاريخ الدفع']

POSITIVE_STATUSES = {'متابعة', 'سداد جزئي', 'واعد بالسداد', 'تم السداد'}
NEGATIVE_STATUSES = {'عدم توصل', 'رافض السداد'}
COMPLETED_STATUSES = {'تم السداد'}
