[theme]
primaryColor = "#00e5a0"
backgroundColor = "#0b132b"
secondaryBackgroundColor = "#1c2541"
textColor = "#ffffff"
font = "sans serif"

[server]
maxUploadSize = 2000
maxMessageSize = 2000
enableCORS = false
enableXsrfProtection = false

[runner]
fastReruns = true

[browser]
gatherUsageStats = false
